### PR TITLE
Fix not working on Gatsby 3+

### LINKED ISSUE #2: query is not allowed as internal field
When running the plugin, I receive the following error:

```
The new node didn't pass validation: child "internal" fails because ["query" is not allowed]
```

### PR DESCRIPTION
**Pull request by DrakenZA**
Closes #2.

This one change seems to have fixed the plugin with the latest gatsby version to date.

### CODE REVIEW

File: gatsby-node.js [hunk 1]
```diff
@@ -24,7 +24,6 @@ exports.sourceNodes = async (
       content: JSON.stringify(pub),
       contentDigest: createContentDigest(pub),
       description: nodeInternalDescription(query),
-      query,
     },
   })
```
Comment (graysonhicks) [inline gatsby-node.js:29]: I think `options.queries[index]` on line 34 could also be removed.

Comment (DrakenZA) [reply gatsby-node.js:29]: Think so. One major issue atm is it seems that the way the plugin is going to the 'next page' of its results is not working. Cant get more than 10 results.

**Comment by janosh** [comment]
Sorry about the huge delay, somehow I was never notified about this PR nor issue #2.

I'll merge this now. However, I no longer use Gatsby myself so can't actively maintain this. If anyone would like to take over the project, let me know.
